### ISSUE TITLE
same results for different videos

### ISSUE THREAD

**Issue by xiaokunyin** [google/uvq#6]
I always get exactly the same results for different videos.  What's the posssible reason for that?

**Comment by yilinwang01** [comment]
We haven't seen that problem before. Did you see any error messages?
Could you reproduce the result using our example video (Gaming_1080P-0ce6_orig.mp4)?

**Comment by jKaushalb** [comment]
i am using windows and getting this weird error.

i have 3 different videos and got the same score.... 
![image](https://user-images.githubusercontent.com/63168354/231363092-58288c0a-0bbe-49df-bcaf-7d8a94014946.png)
![image](https://user-images.githubusercontent.com/63168354/231363229-5b8b3c91-4e11-4f5c-ba56-cda768e948bb.png)

**Comment by nbirkbeck** [comment]
As Yilin suggests, maybe you could share more info about the input video you are testing (e.g., video resolution, duration, codec, etc.) and also the command line arguments so we can help debug. 

I just tested on windows using some compressed versions of the test video in the README:
```
curl -o Gaming_1080P-0ce6_orig.mp4 https://storage.googleapis.com/ugc-dataset/vp9_compressed_videos/Gaming_1080P-0ce6_orig.mp4
# E.g., encode input with several compression settings
for crf in $(seq 40 5 55); do 
  ffmpeg -i Gaming_1080P-0ce6_orig.mp4 -crf ${crf} Gaming_1080P-0ce6_orig_${crf}.mp4; 
done
# Run on all the transcodes generated above
for i in *mp4; do  
   python3 uvq_main.py --input_files="${i%%.mp4},20,$i" --output_dir results --model_dir models; 
done
```
And the results look as expected:
```
cat results/Gaming_1080P-0ce6_orig*/*csv | grep compression_content_distortion
Gaming_1080P-0ce6_orig,compression_content_distortion,4.06072850227356
Gaming_1080P-0ce6_orig_40,compression_content_distortion,3.7577770233154295
Gaming_1080P-0ce6_orig_45,compression_content_distortion,3.4338058471679687
Gaming_1080P-0ce6_orig_50,compression_content_distortion,3.1196170330047606
Gaming_1080P-0ce6_orig_55,compression_content_distortion,2.9693247795104982
```

**Comment by jKaushalb** [comment]
It was an ffmpeg error , it required complete path without spaces, in my user name there is space so command broke down.
So i explicitly added the quotes to filepath and it worked well. I guess  without images it just gives the baseline scores.If images are not extracted flow execution should be stopped.
![image](https://user-images.githubusercontent.com/63168354/231675367-c5045250-c607-49df-bcd4-fb588fbe8637.png)

**Comment by xiaokunyin** [comment]
I think I find the problem for my case. In ReadMe, the command:
python3 uvq_main.py --input_files='Gaming_1080P-0ce6_orig,20,Gaming_1080P-0ce6_orig.mp4' --output_dir results --model_dir models

The --input_files should not have the quotation marks. This would cause the problem that ffmpeg can not get the correct filepath. Because when the script parse the command, the filepath would be `filename'` with the half quote mark.
